version: "3.10"
services:
  gunicorn:
    build: gunicorn
    volumes:
      - /srv/homework5/506-5/shared:/shared

  nginx:
    build: nginx 
    ports:
      - "80:80"
    volumes:
      - /srv/homework5/506-5/shared:/shared
    command: nginx -g 'daemon off;'

